[tools]
go = "latest"
"go:github.com/spf13/cobra-cli" = "latest"
golangci-lint = "latest"
golines = "latest"
goreleaser = "latest"

[tasks]
fetch = "go install"
release = "goreleaser release --clean"
